### ISSUE TITLE
Enable htbac to run with RADICAL Pilot ORTE launch method

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/htbac#5]
Titan aprun launch method can only scale to 100 concurrent `aprun` processes. Scaling more than one `TIES` instance will lead into concurrency conflicts. Ref ticket [1567](https://github.com/radical-cybertools/radical.pilot/issues/1567#issuecomment-368549193). 

## Future Needs
- Build NAMD with OPENMP to enable `ornl.titan-orte`

**Comment by jdakka** [comment]
[Trace](https://github.com/radical-cybertools/htbac/issues/1)

**Comment by jdakka** [comment]
Still blocked by ticket [1572](https://github.com/radical-cybertools/radical.pilot/issues/1572#issuecomment-369303603)

This is no longer an `RP-ORTE` launch problem. We are encountering a `NAMD` incompatibility with `ORTE` (only for ESMACS)

**Comment by mturilli** [comment]
Summary (please feel free to edit if required)

# Requirements for UCL production run of ESMACS on Titan

* UCL requires concurrent execution of ESMACS protocols on Titan. Each run should use > 300 nodes, for a minimum of 12 (i.e., 300/25) concurrent ESMACS protocols executions. A full production run requires investigating ~100 mutations, for a minimum of ~9 (i.e., 100/12) 300 nodes sequential runs.
* UCL uses Titan's default NAMD package compiled against aprun. Aprun does not offer the (weak) scaling required by UCL, i.e., > 50 concurrent aprun processes.
* UCL requires running NAMD on a single node but their physical systems are configured to use mpi. UCL does not want to rewrite their physical systems configurations for a non-mpi run of NAMD on a single node.
* UCL requires CUDA support for performance.

Based on these requirements we are:
* investigating whether/how to compile NAMD with CUDA and OpenMPI support;
* evaluating whether it is possible to open a channel with a dedicated scientific support officer at ORNL to supervise the compilation of NAMD with CUDA and OpenMPI.

**Comment by dww100** [comment]
I think that is a good summary.
I would make one point - WRT the comment that our "physical systems are configured to use mpi". This isn't how I would think about the issue. I see no connection between MPI  and how we configured our system. The issue is that the particular compilation we have access to using OpenMP doesn't support some of the features the default build of NAMD does. The physical systems are configured to use a particular water model (TIP4P) which is a scientific choice not related to the way we wish to run the code.

**Comment by dww100** [comment]
The only place where we can find references to the error we get with OpenMP runs is for a much older version of NAMD (courtesy of @kristofarkas):
http://www.ks.uiuc.edu/Research/namd/mailing_list/namd-l.2009-2010/2768.html
Should we send a message to the list? Otherwise Justin at ANL seems to have links to teh developers and he might be able to ask about this?

**Comment by kristofarkas** [comment]
> * UCL requires running NAMD on a single node but their physical systems are configured to use mpi. 

Our system (that uses TIP4P water model) gives an error while running with the @andre-merzky compiled NAMD (version 2.12, OpenMP, non-CUDA), but does _not_ when run with the NAMD version default to Titan (version 2.12, MPI?, CUDA). The reason for highlighting the TIP4P water model is because this same error is in a [forum post](http://www.ks.uiuc.edu/Research/namd/mailing_list/namd-l.2009-2010/2768.html) where they identify TIP4P as the problem. But this is for NAMD version 2.7! 
> UCL does not want to rewrite their physical systems configurations for a non-mpi run of NAMD on a single node.

Rebuilding with TIP3P would not make sense scientifically.

Based on these observations, I think the problem is not with single vs multi-node, or mpi vs non-mpi, right @mturilli? Maybe the _specific_ NAMD version that @andre-merzky compiled differs from the one on Titan (even though they are both 2.12) and some bug was reintroduced by accident by NAMD devs? We might have to check with them as @dww100 suggested.

**Comment by andre-merzky** [comment]
Thanks all - I would be happy to get guidelines on the specific version and configuration of NAMD you need for these systems.

**Comment by dww100** [comment]
@andre-merzky Our issue at present is we have no idea which version/versions might help. I guess the best option might be to try a nightly build and if that fails 2.11. Sorry we can't be more helpful. I do wonder if the NAMD devs are the people to ask.

**Comment by jdakka** [comment]
@dww100 @andre-merzky I think it makes sense to involve the NAMD developers to some extent. It seems like a needle in a haystack situation otherwise. Compilation is very timely and any convergence on which parameters are needed in NAMD would help tremendously.

**Comment by dww100** [comment]
@andre-merzky What do you think the best way of communicating this is? Do you have, or know someone who has, direct contact with NAMD developers? If not is it best if you contact the mailing list to ask about this. That way you can interact directly with them.

**Comment by dww100** [comment]
@andre-merzky Do you have a copy of the inputs that are causing the error to test with?

**Comment by jdakka** [comment]
@andre-merzky @dww100 @shantenujha @mturilli 

We have a working version of NAMD using CUDA running on Titan with the ORTE launch method in RCT :) 

Thanks to @kristofarkas for finding a pre-compiled version

**Comment by andre-merzky** [comment]
Phantastic!  @kristofarkas : is it possible to find out with what configuration options that NAMD has been compiled?
